### ISSUE TITLE
Same icon datas for different icon names

### ISSUE THREAD

**Issue by BugsOverBugs** [clean/lineawesome_icons#3]
Hey,
your package is really awesome, but I noticed that the `bookmark_1` icon data is the same like `bookmark`. 
There are also other filled icons missing.
In my case a filled `bookmark` is enough.

Thanks for fixing it as soon as possible!

**Comment by darkomenx** [comment]
I also unfortunetely pity notice that the "ellipsis" icon (international standard app icon) is not present into the package.

**Comment by peengle** [comment]
I've just released version 3.0.0 with an updated icon set. Keep in mind that some of the icon names have been changed to match Line Awesome icons v1.3.0.

**Comment by darkomenx** [comment]
OK very thank you @peengle for your works release 👍

**Comment by BugsOverBugs** [comment]
Hey. Wow an update after almost 3 years. 
Unfortunately it sometimes only contains `_solid` icon names for icons that are not solid. This leads to unnecessary breaking changes and confusion. 
In addition, the original issue remains: `bookmark` and `bookmark_solid` share the same icon, so solid is still not solid.

**Comment by TijnvandenEijnde** [comment]
@BugsOverBugs I am running into the same issue, solid icons are not solid at all.
